# fly.toml app configuration file generated for free-pos-backend on 2024-08-03T22:35:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'free-pos-backend'
primary_region = 'sea'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']
[http_service.concurrency]
type = "requests"
soft_limit = 500
hard_limit = 550

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1

[mounts]
destination = "/pb/pb_data"
source = "pb_data"
